#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, re
from pathlib import Path

FORBIDDEN = {
    "STM": ["SAM3X", "SAM4E", "SAME70", "ATSAM", "PMC_SR", "PIOC_PSR", "MCKRDY", "OSCSELS", "NXP-FRDM", "MK22F", "MK64F"],
    "SAM": ["STM32F103xx", "STM32F072", "STM32L476", "NXP-FRDM", "MK22F", "MK64F"],
    "NXP": ["STM32F103xx", "STM32F072", "STM32L476", "SAM3X", "SAM4E", "SAME70", "ATSAM", "PMC_SR", "PIOC_PSR"],
    "UNKNOWN": ["PMC_SR", "PIOC_PSR", "MCKRDY", "OSCSELS"],
}


def family(row: dict) -> str:
    s = " ".join(str(row.get(k, "")) for k in ("svd", "pdf", "mcu", "case_id")).lower()
    if "stm32" in s or "/stm/" in s:
        return "STM"
    if "atsam" in s or "/sam/" in s or "sam3" in s or "sam4" in s or "same70" in s:
        return "SAM"
    if "/nxp/" in s or "mk22" in s or "mk64" in s or "lpc" in s:
        return "NXP"
    return "UNKNOWN"


def main():
    ap = argparse.ArgumentParser(description="Check closed-loop artifacts for cross-family semantic residue.")
    ap.add_argument("--roots", required=True, help="roots.txt generated by the parallel runner")
    ap.add_argument("--manifest", default="workdir/newmulti_ab/targets_manifest.jsonl")
    args = ap.parse_args()

    manifest = {}
    mp = Path(args.manifest)
    if mp.exists():
        for line in mp.read_text(errors="replace").splitlines():
            if line.strip():
                r = json.loads(line)
                manifest[r["case_id"]] = r

    any_issue = False
    print("== semantic residue check ==")
    for line in Path(args.roots).read_text(errors="replace").splitlines():
        if not line.strip():
            continue
        case_id, root, _log = line.split(maxsplit=2)
        root = Path(root)
        fam = family(manifest.get(case_id, {"case_id": case_id}))
        toks = FORBIDDEN.get(fam, [])
        hits = []
        for p in root.rglob("*"):
            if not p.is_file() or p.suffix not in {".json", ".log", ".md", ".csv", ".txt"}:
                continue
            if "replay_trace" in p.name:
                continue
            txt = p.read_text(errors="replace")
            for tok in toks:
                pattern = r"(?<![A-Za-z0-9_])" + re.escape(tok) + r"(?![A-Za-z0-9_])"
                if re.search(pattern, txt, flags=re.I):
                    hits.append((tok, str(p)))
                    break
        print(f"\nCASE: {case_id} FAMILY: {fam}")
        if hits:
            any_issue = True
            print("  ISSUE forbidden semantic tokens:")
            for tok, path in hits[:30]:
                print("   ", tok, path)
        else:
            print("  OK no forbidden semantic residue")
    print("\nRESULT:", "ISSUE" if any_issue else "OK")
    raise SystemExit(1 if any_issue else 0)


if __name__ == "__main__":
    main()
