#!/usr/bin/env python3
from __future__ import annotations
import argparse, json
from collections import Counter
from pathlib import Path


def main():
    ap = argparse.ArgumentParser(description="Summarize NewMultiFuzz closed-loop roots.txt results.")
    ap.add_argument("--roots", required=True, help="roots.txt generated by run_multi_target_closed_loop_parallel.sh")
    args = ap.parse_args()

    root_list = Path(args.roots)
    decision_counter = Counter()
    bad = []

    print("== closed-loop summary ==")
    print("ROOT_LIST:", root_list)
    for line in root_list.read_text(errors="replace").splitlines():
        if not line.strip():
            continue
        case_id, root, log = line.split(maxsplit=2)
        root = Path(root)
        print("\nCASE:", case_id)
        print("ROOT:", root)
        epochs = sorted((root / "epochs").glob("epoch_*"), key=lambda p: int(p.name.split("_")[-1]))
        print("epoch_count:", len(epochs))
        for ep in epochs:
            fs = ep / "final_summary.json"
            if not fs.exists():
                print(" ", ep.name, "NO final_summary")
                bad.append((case_id, ep.name, "missing_final_summary"))
                continue
            d = json.loads(fs.read_text())
            decision = d.get("final_decision")
            decision_counter[decision] += 1
            rg = d.get("repeat_gate_stats") or {}
            print(
                " ", ep.name,
                "script_success=", d.get("script_success"),
                "failed=", d.get("failed"),
                "decision=", decision,
                "repeat_gate=", rg,
            )
            if d.get("script_success") is not True or d.get("failed") is True or decision == "script_failed":
                bad.append((case_id, ep.name, decision))
        state = root / "state/closed_loop_state.json"
        if state.exists():
            s = json.loads(state.read_text())
            print("scheduler:", s.get("scheduler"))
            print("portfolio:", {k: len(v) for k, v in (s.get("portfolio") or {}).items() if isinstance(v, list)})

    print("\n== decision counts ==")
    for k, v in decision_counter.most_common():
        print(k, v)
    print("\nBAD:", bad if bad else "none")


if __name__ == "__main__":
    main()
